---
- name: Print some debug information
  vars:
    msg: |
        Ansible Distribution: {{ ansible_distribution }}
        Ansible Dist version: {{ ansible_distribution_version }}
        Ansible OS family: {{ ansible_os_family }}
  debug:
    msg: "{{ msg.split('\n') }}"
- name: Install latest version on Archlinux
  community.general.pacman:
    name:
      - wireguard-tools
    state: present
  when: ansible_distribution == 'Archlinux'

- name: Install latest version on Debian
  ansible.builtin.apt:
    name: wireguard
    state: present
  when: ansible_distribution == 'Debian'

- name: Install latest version on openSUSE
  community.general.zypper:
    name: wireguard-tools
    state: present
  when: ansible_os_family == "Suse"
